import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f1f0e4',
  '--slot4-page-text': '#202118',
  '--slot4-panel-bg': '#ebe7d7',
  '--slot4-surface-bg': '#fbfaf3',
  '--slot4-muted-text': '#6a6d5a',
  '--slot4-soft-muted-text': '#8a8e7a',
  '--slot4-accent': '#3e3f29',
  '--slot4-accent-fill': '#3e3f29',
  '--slot4-accent-soft': '#d8d2bf',
  '--slot4-on-accent': '#f1f0e4',
  '--slot4-dark-bg': '#10100c',
  '--slot4-dark-text': '#f4f1e8',
  '--slot4-media-bg': '#d9d3c4',
  '--slot4-cream': '#fbfaf3',
  '--slot4-warm': '#ebe7d7',
  '--slot4-lavender': '#d8d2bf',
  '--slot4-gray': '#d9d6cb',
  '--slot4-body-gradient': 'radial-gradient(circle at top, rgba(188,168,141,0.28), transparent 38%), linear-gradient(180deg, #f7f5ed 0%, #f1f0e4 30%, #ece9de 100%)',
  '--editable-page-bg': '#f1f0e4',
  '--editable-page-text': '#202118',
  '--editable-container': '1220px',
  '--editable-border': 'rgba(62,63,41,0.14)',
  '--editable-nav-bg': '#080807',
  '--editable-nav-text': '#f4f1e8',
  '--editable-nav-active': '#f1f0e4',
  '--editable-nav-active-text': '#080807',
  '--editable-cta-bg': '#3e3f29',
  '--editable-cta-text': '#f1f0e4',
  '--editable-search-bg': '#fbfaf3',
  '--editable-footer-bg': '#080807',
  '--editable-footer-text': '#f4f1e8',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-on-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_40px_rgba(32,33,24,0.07)]',
  shadowStrong: 'shadow-[0_30px_80px_rgba(16,16,12,0.18)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(12,12,10,0.04),rgba(12,12,10,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[0.95fr_1.05fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[220px] shrink-0 snap-start sm:w-[260px]',
  },
  type: {
    eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.32em] text-[var(--slot4-accent)]',
    heroTitle: 'text-5xl font-semibold leading-[0.92] tracking-[-0.05em] sm:text-6xl lg:text-[4.65rem]',
    sectionTitle: 'text-4xl font-semibold leading-[0.96] tracking-[-0.045em] sm:text-5xl',
    body: 'text-base leading-8',
  },
  surface: {
    card: `rounded-[1.6rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.6rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.6rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-none bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold uppercase tracking-[0.16em] text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:brightness-95',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-none border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold uppercase tracking-[0.16em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-none bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold uppercase tracking-[0.16em] text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:brightness-95',
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.35rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/5]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_24px_52px_rgba(32,33,24,0.14)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Start with a strong editorial shell: dark utility header, warm background, pale content surfaces, and bold serif headlines.',
  'Keep homepage composition inside src/editable/sections/HomeSections.tsx so home can be reshaped without touching route logic.',
  'Use at least three card silhouettes across major feeds: image-first, horizontal directory, and compact list styles.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Always use postHref() or the task route when linking so task-specific detail routes keep working.',
] as const
